#!/usr/bin/env python3

import logging
import os

import tornado.ioloop
import tornado.options
import tornado.tcpserver

# Local modules

from irc import IRCHandler
from telegram import TelegramHandler

# IRC Telegram Daemon

class IRCTelegramd(tornado.tcpserver.TCPServer):
    def __init__(self, address=None, port=6667, config_dir=None, **settings):
        tornado.tcpserver.TCPServer.__init__(self)

        self.logger     = logging.getLogger()
        self.address    = address or '127.0.0.1'
        self.port       = port
        self.config_dir = config_dir or os.path.expanduser('~/.config/irgramd')
        self.irc_handler = None
        self.tg_handler  = None

        if not os.path.exists(self.config_dir):
            os.makedirs(self.config_dir)

    async def handle_stream(self, stream, address):
        await self.irc_handler.run(stream, address)

    def run(self):
        self.listen(self.port, self.address)
        self.logger.info('irgramd listening on %s:%s', self.address, self.port)
        self.logger.info('Configuration Directory: %s', self.config_dir)

        self.irc_handler = IRCHandler(self.config_dir)
        self.tg_handler = TelegramHandler(self.irc_handler, self.config_dir)
        self.irc_handler.set_telegram(self.tg_handler)
        self.tg_handler.initialize_telegram()

        tornado.ioloop.IOLoop.current().start()


# Main Execution

if __name__ == '__main__':
    tornado.options.define('address', default=None, help='Address to listen on.')
    tornado.options.define('port', default=6667, help='Port to listen on.')
    tornado.options.define('config_dir', default=None, help='Configuration directory')
    tornado.options.parse_command_line()

    options    = tornado.options.options.as_dict()
    irc_server = IRCTelegramd(**options)
    irc_server.run()
